#pragma once
#include <nxemu-core\hle\Kernel\Service.h>

class IFileSystemProxy :
    public CService
{
public:
    enum Method
    {
        OpenFileSystem = 0,
        SetCurrentProcess = 1,
        OpenDataFileSystemByCurrentProcess = 2,
        OpenFileSystemWithPatch = 7,
        OpenFileSystemWithId = 8,
        OpenDataFileSystemByProgramId = 9,
        OpenBisFileSystem = 11,
        OpenBisStorage = 12,
        InvalidateBisCache = 13,
        OpenHostFileSystem = 17,
        OpenSdCardFileSystem = 18,
        FormatSdCardFileSystem = 19,
        DeleteSaveDataFileSystem = 21,
        CreateSaveDataFileSystem = 22,
        CreateSaveDataFileSystemBySystemSaveDataId = 23,
        RegisterSaveDataFileSystemAtomicDeletion = 24,
        DeleteSaveDataFileSystemBySaveDataSpaceId = 25,
        FormatSdCardDryRun = 26,
        IsExFatSupported = 27,
        DeleteSaveDataFileSystemBySaveDataAttribute = 28,
        OpenGameCardStorage = 30,
        OpenGameCardFileSystem = 31,
        ExtendSaveDataFileSystem = 32,
        DeleteCacheStorage = 33,
        GetCacheStorageSize = 34,
        CreateSaveDataFileSystemWithHashSalt = 35,
        OpenHostFileSystemWithOption = 36,
        OpenSaveDataFileSystem = 51,
        OpenSaveDataFileSystemBySystemSaveDataId = 52,
        OpenReadOnlySaveDataFileSystem = 53,
        ReadSaveDataFileSystemExtraDataBySaveDataSpaceId = 57,
        ReadSaveDataFileSystemExtraData = 58,
        WriteSaveDataFileSystemExtraData = 59,
        OpenSaveDataInfoReader = 60,
        OpenSaveDataInfoReaderBySaveDataSpaceId = 61,
        OpenSaveDataInfoReaderOnlyCacheStorage = 62,
        OpenSaveDataInternalStorageFileSystem = 64,
        UpdateSaveDataMacForDebug = 65,
        WriteSaveDataFileSystemExtraDataWithMask = 66,
        FindSaveDataWithFilter = 67,
        OpenSaveDataInfoReaderWithFilter = 68,
        ReadSaveDataFileSystemExtraDataBySaveDataAttribute = 69,
        WriteSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute = 70,
        ReadSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute = 71,
        OpenSaveDataMetaFile = 80,
        OpenSaveDataTransferManager = 81,
        OpenSaveDataTransferManagerVersion2 = 82,
        OpenSaveDataTransferProhibiter = 83,
        ListAccessibleSaveDataOwnerId = 84,
        OpenSaveDataTransferManagerForSaveDataRepair = 85,
        OpenSaveDataMover = 86,
        OpenImageDirectoryFileSystem = 100,
        OpenContentStorageFileSystem = 110,
        OpenCloudBackupWorkStorageFileSystem = 120,
        OpenCustomStorageFileSystem = 130,
        OpenDataStorageByCurrentProcess = 200,
        OpenDataStorageByProgramId = 201,
        OpenDataStorageByDataId = 202,
        OpenPatchDataStorageByCurrentProcess = 203,
        OpenDataFileSystemWithProgramIndex = 204,
        OpenDataStorageWithProgramIndex = 205,
        OpenDeviceOperator = 400,
        OpenSdCardDetectionEventNotifier = 500,
        OpenGameCardDetectionEventNotifier = 501,
        OpenSystemDataUpdateEventNotifier = 510,
        NotifySystemDataUpdateEvent = 511,
        SimulateDeviceDetectionEvent = 520,
        SetCurrentPosixTime = 600,
        QuerySaveDataTotalSize = 601,
        VerifySaveDataFileSystem = 602,
        CorruptSaveDataFileSystem = 603,
        CreatePaddingFile = 604,
        DeleteAllPaddingFiles = 605,
        GetRightsId = 606,
        RegisterExternalKey = 607,
        UnregisterAllExternalKey = 608,
        GetRightsIdByPath = 609,
        GetRightsIdAndKeyGenerationByPath = 610,
        SetCurrentPosixTimeWithTimeDifference = 611,
        GetFreeSpaceSizeForSaveData = 612,
        VerifySaveDataFileSystemBySaveDataSpaceId = 613,
        CorruptSaveDataFileSystemBySaveDataSpaceId = 614,
        QuerySaveDataInternalStorageTotalSize = 615,
        GetSaveDataCommitId = 616,
        UnregisterExternalKey = 617,
        SetSdCardEncryptionSeed = 620,
        SetSdCardAccessibility = 630,
        IsSdCardAccessible = 631,
        IsSignedSystemPartitionOnSdCardValid = 640,
        OpenAccessFailureDetectionEventNotifier = 700,
        GetAccessFailureDetectionEvent = 701,
        IsAccessFailureDetected = 702,
        ResolveAccessFailure = 710,
        AbandonAccessFailure = 720,
        GetAndClearErrorInfo = 800,
        RegisterProgramIndexMapInfo = 810,
        SetBisRootForHost = 1000,
        SetSaveDataSize = 1001,
        SetSaveDataRootPath = 1002,
        DisableAutoSaveDataCreation = 1003,	
        SetGlobalAccessLogMode = 1004,
        GetGlobalAccessLogMode = 1005,
        OutputAccessLogToSdCard = 1006,
        RegisterUpdatePartition = 1007,
        OpenRegisteredUpdatePartition = 1008,
        GetAndClearMemoryReportInfo = 1009,
        SetDataStorageRedirectTarget = 1010,
        GetProgramIndexForAccessLog = 1011,
        GetFsStackUsage = 1012,
        UnsetSaveDataRootPath = 1013,
        OutputMultiProgramTagAccessLog = 1014,
        OverrideSaveDataTransferTokenSignVerificationKey = 1100,
        CorruptSaveDataFileSystemByOffset = 1110,
        OpenMultiCommitManager = 1200,
        OpenBisWiper = 1300,
    };
    static CKernelObjectPtr CreateInstance(CSwitchSystem & System);

    //__interface IService
    bool Connect(void);
    ResultCode CallMethod(CIPCRequest & Request);
    const char * Name(void) const { return "IFileSystemProxy"; }

private:
    IFileSystemProxy(void);
    IFileSystemProxy(const IFileSystemProxy&);
    IFileSystemProxy& operator=(const IFileSystemProxy&);

    IFileSystemProxy(CSwitchSystem & System);
};