#pragma once
#include <nxemu-core\hle\Kernel\Service.h>

class IFileSystemProxy :
    public CService
{
public:
    enum Method
    {
        Method_OpenFileSystem = 0,
        Method_SetCurrentProcess = 1,
        Method_OpenDataFileSystemByCurrentProcess = 2,
        Method_OpenFileSystemWithPatch = 7,
        Method_OpenFileSystemWithId = 8,
        Method_OpenDataFileSystemByProgramId = 9,
        Method_OpenBisFileSystem = 11,
        Method_OpenBisStorage = 12,
        Method_InvalidateBisCache = 13,
        Method_OpenHostFileSystem = 17,
        Method_OpenSdCardFileSystem = 18,
        Method_FormatSdCardFileSystem = 19,
        Method_DeleteSaveDataFileSystem = 21,
        Method_CreateSaveDataFileSystem = 22,
        Method_CreateSaveDataFileSystemBySystemSaveDataId = 23,
        Method_RegisterSaveDataFileSystemAtomicDeletion = 24,
        Method_DeleteSaveDataFileSystemBySaveDataSpaceId = 25,
        Method_FormatSdCardDryRun = 26,
        Method_IsExFatSupported = 27,
        Method_DeleteSaveDataFileSystemBySaveDataAttribute = 28,
        Method_OpenGameCardStorage = 30,
        Method_OpenGameCardFileSystem = 31,
        Method_ExtendSaveDataFileSystem = 32,
        Method_DeleteCacheStorage = 33,
        Method_GetCacheStorageSize = 34,
        Method_CreateSaveDataFileSystemWithHashSalt = 35,
        Method_OpenHostFileSystemWithOption = 36,
        Method_OpenSaveDataFileSystem = 51,
        Method_OpenSaveDataFileSystemBySystemSaveDataId = 52,
        Method_OpenReadOnlySaveDataFileSystem = 53,
        Method_ReadSaveDataFileSystemExtraDataBySaveDataSpaceId = 57,
        Method_ReadSaveDataFileSystemExtraData = 58,
        Method_WriteSaveDataFileSystemExtraData = 59,
        Method_OpenSaveDataInfoReader = 60,
        Method_OpenSaveDataInfoReaderBySaveDataSpaceId = 61,
        Method_OpenSaveDataInfoReaderOnlyCacheStorage = 62,
        Method_OpenSaveDataInternalStorageFileSystem = 64,
        Method_UpdateSaveDataMacForDebug = 65,
        Method_WriteSaveDataFileSystemExtraDataWithMask = 66,
        Method_FindSaveDataWithFilter = 67,
        Method_OpenSaveDataInfoReaderWithFilter = 68,
        Method_ReadSaveDataFileSystemExtraDataBySaveDataAttribute = 69,
        Method_WriteSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute = 70,
        Method_ReadSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute = 71,
        Method_OpenSaveDataMetaFile = 80,
        Method_OpenSaveDataTransferManager = 81,
        Method_OpenSaveDataTransferManagerVersion2 = 82,
        Method_OpenSaveDataTransferProhibiter = 83,
        Method_ListAccessibleSaveDataOwnerId = 84,
        Method_OpenSaveDataTransferManagerForSaveDataRepair = 85,
        Method_OpenSaveDataMover = 86,
        Method_OpenImageDirectoryFileSystem = 100,
        Method_OpenContentStorageFileSystem = 110,
        Method_OpenCloudBackupWorkStorageFileSystem = 120,
        Method_OpenCustomStorageFileSystem = 130,
        Method_OpenDataStorageByCurrentProcess = 200,
        Method_OpenDataStorageByProgramId = 201,
        Method_OpenDataStorageByDataId = 202,
        Method_OpenPatchDataStorageByCurrentProcess = 203,
        Method_OpenDataFileSystemWithProgramIndex = 204,
        Method_OpenDataStorageWithProgramIndex = 205,
        Method_OpenDeviceOperator = 400,
        Method_OpenSdCardDetectionEventNotifier = 500,
        Method_OpenGameCardDetectionEventNotifier = 501,
        Method_OpenSystemDataUpdateEventNotifier = 510,
        Method_NotifySystemDataUpdateEvent = 511,
        Method_SimulateDeviceDetectionEvent = 520,
        Method_SetCurrentPosixTime = 600,
        Method_QuerySaveDataTotalSize = 601,
        Method_VerifySaveDataFileSystem = 602,
        Method_CorruptSaveDataFileSystem = 603,
        Method_CreatePaddingFile = 604,
        Method_DeleteAllPaddingFiles = 605,
        Method_GetRightsId = 606,
        Method_RegisterExternalKey = 607,
        Method_UnregisterAllExternalKey = 608,
        Method_GetRightsIdByPath = 609,
        Method_GetRightsIdAndKeyGenerationByPath = 610,
        Method_SetCurrentPosixTimeWithTimeDifference = 611,
        Method_GetFreeSpaceSizeForSaveData = 612,
        Method_VerifySaveDataFileSystemBySaveDataSpaceId = 613,
        Method_CorruptSaveDataFileSystemBySaveDataSpaceId = 614,
        Method_QuerySaveDataInternalStorageTotalSize = 615,
        Method_GetSaveDataCommitId = 616,
        Method_UnregisterExternalKey = 617,
        Method_SetSdCardEncryptionSeed = 620,
        Method_SetSdCardAccessibility = 630,
        Method_IsSdCardAccessible = 631,
        Method_IsSignedSystemPartitionOnSdCardValid = 640,
        Method_OpenAccessFailureDetectionEventNotifier = 700,
        Method_GetAccessFailureDetectionEvent = 701,
        Method_IsAccessFailureDetected = 702,
        Method_ResolveAccessFailure = 710,
        Method_AbandonAccessFailure = 720,
        Method_GetAndClearErrorInfo = 800,
        Method_RegisterProgramIndexMapInfo = 810,
        Method_SetBisRootForHost = 1000,
        Method_SetSaveDataSize = 1001,
        Method_SetSaveDataRootPath = 1002,
        Method_DisableAutoSaveDataCreation = 1003,
        Method_SetGlobalAccessLogMode = 1004,
        Method_GetGlobalAccessLogMode = 1005,
        Method_OutputAccessLogToSdCard = 1006,
        Method_RegisterUpdatePartition = 1007,
        Method_OpenRegisteredUpdatePartition = 1008,
        Method_GetAndClearMemoryReportInfo = 1009,
        Method_SetDataStorageRedirectTarget = 1010,
        Method_GetProgramIndexForAccessLog = 1011,
        Method_GetFsStackUsage = 1012,
        Method_UnsetSaveDataRootPath = 1013,
        Method_OutputMultiProgramTagAccessLog = 1014,
        Method_OverrideSaveDataTransferTokenSignVerificationKey = 1100,
        Method_CorruptSaveDataFileSystemByOffset = 1110,
        Method_OpenMultiCommitManager = 1200,
        Method_OpenBisWiper = 1300,
    };
    static CKernelObjectPtr CreateInstance(CSwitchSystem & System);

    //__interface IService
    bool Connect(void);
    ResultCode CallMethod(CIPCRequest & Request);
    const char * Name(void) const { return "IFileSystemProxy"; }

private:
    IFileSystemProxy(void);
    IFileSystemProxy(const IFileSystemProxy&);
    IFileSystemProxy& operator=(const IFileSystemProxy&);

    IFileSystemProxy(CSwitchSystem & System);

	void ProcessOpenSaveDataFileSystem(CIPCRequest & Request);
    void ProcessGetGlobalAccessLogMode(CIPCRequest & Request);
};